# Generated by Django 4.2.30 on 2026-04-25 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carrier_name', models.CharField(max_length=255)),
                ('freight_charges', models.DecimalField(decimal_places=2, max_digits=15)),
                ('origin_charges', models.DecimalField(decimal_places=2, max_digits=15)),
                ('destination_charges', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_charges', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('transit_time_days', models.IntegerField()),
                ('quote_validity_days', models.IntegerField()),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bid',
                'ordering': ['total_charges', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('bid_start_time', models.DateTimeField()),
                ('bid_close_time', models.DateTimeField()),
                ('forced_close_time', models.DateTimeField()),
                ('pickup_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('force_closed', 'Force Closed'), ('awarded', 'Awarded')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rfqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rfq',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prev_close_time', models.DateTimeField()),
                ('new_close_time', models.DateTimeField()),
                ('trigger_reason', models.CharField(choices=[('bid', 'Bid Received in Trigger Window'), ('rank_change', 'Rank Change in Trigger Window'), ('l1_change', 'L1 Rank Change in Trigger Window'), ('manual', 'Manual Extension')], max_length=20)),
                ('extended_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_mins', models.IntegerField()),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_history', to='auction_system.rfq')),
                ('trigger_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction_system.bid')),
            ],
            options={
                'db_table': 'extension_history',
                'ordering': ['-extended_at'],
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction_system.rfq'),
        ),
        migrations.AddField(
            model_name='bid',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuctionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('bid_received', 'Bid Received'), ('rank_changed', 'Rank Changed'), ('l1_changed', 'L1 Changed'), ('extended', 'Auction Extended'), ('closed', 'Auction Closed'), ('force_closed', 'Auction Force Closed')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction_system.bid')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='auction_system.rfq')),
            ],
            options={
                'db_table': 'auction_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_window_mins', models.IntegerField(default=10, help_text='Minutes before close time to start monitoring', validators=[django.core.validators.MinValueValidator(1)])),
                ('extension_duration_mins', models.IntegerField(default=5, help_text='Minutes to extend auction when triggered', validators=[django.core.validators.MinValueValidator(1)])),
                ('trigger_type', models.CharField(choices=[('bid', 'Bid Received'), ('rank_change', 'Any Rank Change'), ('l1_change', 'L1 Rank Change')], default='bid', help_text='What type of activity triggers extension', max_length=20)),
                ('current_close_time', models.DateTimeField(blank=True, null=True)),
                ('last_extension_at', models.DateTimeField(blank=True, null=True)),
                ('extension_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auction_system.rfq')),
            ],
            options={
                'db_table': 'auction',
            },
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['reference_id'], name='rfq_referen_97154e_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status'], name='rfq_status_196359_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['bid_close_time'], name='rfq_bid_clo_d219d7_idx'),
        ),
        migrations.AddIndex(
            model_name='extensionhistory',
            index=models.Index(fields=['rfq', '-extended_at'], name='extension_h_rfq_id_dae005_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['rfq', '-created_at'], name='bid_rfq_id_923063_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['supplier'], name='bid_supplie_ad3268_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['total_charges'], name='bid_total_c_ade6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionevent',
            index=models.Index(fields=['rfq', '-created_at'], name='auction_eve_rfq_id_304aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionevent',
            index=models.Index(fields=['event_type'], name='auction_eve_event_t_a68a79_idx'),
        ),
    ]
